[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
array2d = "0.2.1"
itertools = "0.10.5"
pathfinding = "4.0.0"
regex = "1"
